### ISSUE TITLE
It doesn't work on my server.

### ISSUE THREAD

**Issue by Chrithon** [Elkien3/cars#3]
Result:
> 2020-07-20 13:57:53: ERROR[Main]: /home/chris/minetest/bin/../mods/cars/init.lua:319: '=' expected near 'next

But the mod works on my Windows computer(with GUI).
What's wrong with my server? I haven't modified the source code.
Server operating system: Ubuntu 18.04 LTS(Alibaba Cloud ECS)

**Comment by Elkien3** [comment]
Hmm, the only thing I can think of is if for some reason "goto" isn't in your lua install.
I guess make sure lua and minetest are up to date and see if the issue remains.

**Comment by Chrithon** [comment]
I changed to Ubuntu 20.04. I'll try to update my Lua. If the issue remains, I'll contact you. Please don't close the issue. Thx.

**Comment by Chrithon** [comment]
Oops, the issue still remains.
![issue-1](https://user-images.githubusercontent.com/18738631/88016895-0bdf5380-cb57-11ea-9600-23b37c291be6.png)

**Comment by Chrithon** [comment]
I've upgraded my Minetest to 5.4.0, but the issue remains.

**Comment by Chrithon** [comment]
I user your city_sim(modified) server suite(https://github.com/Elkien3/citysim_game), but the issue remains.

**Comment by Chrithon** [comment]
I found a replacement way. Thank you for your help.
